name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Your build commands here (if needed)
          echo "Build step here"

      - name: Test
        run: |
          # Your test commands here (if needed)
          echo "Test step here"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to S3
        uses: w9jds/s3-deploy@v1
        with:
          args: --acl public-read --follow-symlinks --delete
          dir: ./  # Path to your application files to deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: <your-aws-region>
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        if: success()
