name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Your build commands here (if needed)
          echo "Build step here"

      - name: Test
        run: |
          # Your test commands here (if needed)
          echo "Test step here"

      - name: Archive Files
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: .  # Path to your application files to deploy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact
          path: ./deployed-files
      - name: Deploy to S3
        run: |
          aws s3 sync ./deployed-files s3://my-static-web-app01/
          echo "Sync completed"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: success()
