name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build
        run: |
          # Your build commands here (none needed for a simple HTML file)
          echo "No build step required"

      - name: Test
        run: |
          # Your test commands here (none needed for a simple HTML file)
          echo "No tests required"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Deploy to S3
        uses: jakejarvis/s3-sync-action@v0.5.3
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: success()
